name: luno_launcher
description: "A minimalist launcher for Android."
publish_to: 'none'
version: 0.1.0

# Specify supported platforms - Android only
platforms:
  android: # Only allow Android platform

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  installed_apps: ^1.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  uuid: ^4.2.1
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
